services:
  prometheus-ctn:
    image: prom/prometheus:latest
    container_name: prometheus-ctn
    ports:
      - "9090:9090"
    networks:
      - dev-tools-network
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus-storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana-ctn:
    image: grafana/grafana:latest
    container_name: grafana-ctn
    ports:
      - "3000:3000"
    networks:
      - dev-tools-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  alertmanager-ctn:
    image: prom/alertmanager:latest
    container_name: alertmanager-ctn
    ports:
      - "9093:9093"
    networks:
      - dev-tools-network
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-storage:/alertmanager

  node-exporter-ctn:
    image: prom/node-exporter:latest
    container_name: node-exporter-ctn
    ports:
      - "9100:9100"
    networks:
      - dev-tools-network

networks:
  dev-tools-network:
    external: true

volumes:
  grafana-storage:
  prometheus-storage:
  alertmanager-storage: